apiVersion: v1
kind: PersistentVolume
metadata:
  name: ms-service
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: /h2hsit
    server: 10.211.68.4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
