apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-service-pvc
  namespace: automation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: ms-service
