apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ms-setup-portal-app-ops
subjects:
  - kind: ServiceAccount
    name: az-devops-deployment
    namespace: automation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-ops
